# Copyright (C) 2025 Actian Corp.
# All Rights Reserved.

services:
  actian-mcp-server:
    image: ${MCP_SERVER_CONTAINER_IMAGE_NAME}:${MCP_SERVER_CONTAINER_VERSION}
    container_name: ${MCP_SERVER_CONTAINER_NAME}
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ${CONF_FILE}:/app/conf.json:ro
    ports:
      - "${MCP_SERVER_PORT_OUTSIDE_CONTAINER}:${MCP_SERVER_PORT_INSIDE_CONTAINER}"
    extra_hosts:
      - "localhost:host-gateway"
    restart: unless-stopped